#ifndef FH_PROTOCOL_H
#define FH_PROTOCOL_H

enum fh_http_status
{
	FH_HTTP_OK = 200,
	FH_HTTP_BAD_REQUEST = 400,
	FH_HTTP_UNAUTHORIZED = 401,
	FH_HTTP_FORBIDDEN = 403,
	FH_HTTP_NOT_FOUND = 404,
	FH_HTTP_METHOD_NOT_ALLOWED = 405,
	FH_HTTP_REQUEST_URI_TOO_LONG = 414,
	FH_HTTP_INTERNAL_SERVER_ERROR = 500,
	FH_HTTP_SERVICE_UNAVAILABLE = 501,
	FH_HTTP_HTTP_VERSION_NOT_SUPPORTED = 505,
};

typedef enum fh_http_status fh_status_t;

#endif /* FH_PROTOCOL_H */
