AC_DEFUN([LIBTEST_INIT], [
    AC_REQUIRE_AUX_FILE([runtest])

    LIBTEST_DIR='$(top_srcdir)/libtest'
    LIBTEST_LA='$(top_builddir)/libtest/libtest.la'
    LIBTEST_RUNTEST='$(top_srcdir)/build-aux/runtest'

    LIBTEST_RUNTEST_FLAGS_DEFAULT=""
    test "$CI" = "true" && LIBTEST_RUNTEST_FLAGS_DEFAULT="--log-dir logs"

    AC_ARG_VAR([LIBTEST_RUNTEST_FLAGS], [Flags to be passed to build-aux/runtest])
    : ${LIBTEST_RUNTEST_FLAGS:="$LIBTEST_RUNTEST_FLAGS_DEFAULT"}

    AC_SUBST([LIBTEST_DIR])
    AC_SUBST([LIBTEST_LA])
    AC_SUBST([LIBTEST_RUNTEST])
    AC_SUBST([LIBTEST_RUNTEST_FLAGS])
    AC_SUBST([LIBTEST_RUNTEST_EXEC], ['MAKEFLAGS="$(MAKEFLAGS)" $(LIBTEST_RUNTEST) $(LIBTEST_RUNTEST_FLAGS) '])
    AC_SUBST([LIBTEST_RUNTEST_CLEANUP_EXEC], ['$(LIBTEST_RUNTEST) $(LIBTEST_RUNTEST_FLAGS) --clear-logs'])
])
