#!/bin/sh
#
# This script is used to run a command under Valgrind with the appropriate
# options for debugging memory issues. It is intended to be used in a build
# system or testing environment.
#
# This file is part of OSN freehttpd.
#
# Copyright (C) 2025  OSN Developers.
#
# OSN freehttpd is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# OSN freehttpd is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with OSN freehttpd.  If not, see <https://www.gnu.org/licenses/>.

if [ -z "$1" ]; then
    echo "Usage: $0 <command>" >&2
    exit 1
fi

: ${VALGRIND:=valgrind}

exec "$VALGRIND" \
    -s \
    --leak-check=full \
    --show-leak-kinds=all \
    --track-origins=yes \
    --error-exitcode=1 \
    --trace-children=yes \
    $@
