#!/bin/sh

DOMAIN=onesoftnet.eu.org
ADMIN_USER=rakinar2
MAIL_SUBJECT_PREFIX="[git:freehttpd] "

lock="/tmp/git-hook-freehttpd-auto-version"

notify_admin ()
{
	SUBJECT=''

	if test "$1" -eq 1; then
		SUBJECT="All jobs succeeded"
	else
		SUBJECT="Some jobs failed"
	fi

    mail -s "${MAIL_SUBJECT_PREFIX}${SUBJECT}" -A "$onetime_log" "$ADMIN_USER" <<EOF
Hi there,

This is the Git Hook System at $DOMAIN.  A post-receive job was scheduled
to be run at $2.

The log files of the result should be available as an attachment of this email.

--
Git Hook System at onesoftnet.eu.org
EOF
}

run_job ()
{
	echo "Running job"
	return 0
}

daemon_mode ()
{
	onetime_log="/tmp/git-hook-freehttpd-post-receive.log"
	start_date=`date`
	git_lock="/tmp/freehttpd-git-push-lock"

	rm -f "$onetime_log"
	exec >> "$onetime_log" 2>&1

	echo "Post-receive job triggered at $(date)"
	echo "$(date "+%s") $$" > "$lock"

	echo "Waiting 60 seconds..."
	sleep 60

	echo 1 > "$git_lock"
	set -x

	if run_job; then
		echo "Executed successfully"
		set +x
		notify_admin 1 "$start_date"
	else
		echo "Execution failed"
		set +x
		notify_admin 0 "$start_date"
	fi

	rm -f "$git_lock"
	cat "$onetime_log" >> /var/log/git-hook-freehttpd-auto-version-daemon.log
	rm -f "$onetime_log" "$lock"

	exit 0
}

if test "$1" = "daemon"; then
	daemon_mode $@
	exit 0
fi

read oldrev newrev ref

if test "$ref" != "refs/heads/main"; then
	echo "Ref '$ref' will not trigger a post-receive job"
	exit 0
fi

if test -f "$lock"; then
	time=`cat "$lock" | cut -d' ' -f1`
	pid=`cat "$lock" | cut -d' ' -f2`
	echo "Canceling existing post-receive job (scheduled at $(date --date="@${time}"))..."
	rm -f "$lock"
	kill -TERM "$pid" 2>/dev/null
fi

echo "Queuing post-receive job to be run in 1 minute..."
nohup sh "$0" daemon >/dev/null 2>&1 &
echo "Done"
