#!/bin/sh

GPG_HOME="/srv/git/trusted-keys"
git_lock="/tmp/freehttpd-git-push-lock"

if test -f "$git_lock"; then
	echo "Cannot accept your push at this moment. Please try again in a bit."
	exit 1
fi

set -e
read oldrev newrev refname

if [ -z "$GIT_PUSH_CERT_KEY" ] || [ "$GIT_PUSH_CERT_NONCE_STATUS" != "OK" ]; then
    echo "Invalid push certificate"
    exit 1
fi

if test -z "$(gpg --homedir "$GPG_HOME" --list-keys --keyid-format=long 2>/dev/null | grep "$GIT_PUSH_CERT_KEY")"; then
    echo "Unauthorized push certiciate key ID"
    exit 1
fi

exit 0
