#!/bin/sh

if test $# -lt 1; then
	echo "Usage: $0 <bare_repo_path>" >&2
	exit 1
fi

path="$1"

if ! test -d "$path"; then
	echo "$0: Repository '$path' does not exist" >&2
	exit 1
fi

dir=`dirname "$0"`

set -xe

install -T -m 0755 "$dir/git-pre-receive" "$path/hooks/pre-receive"
install -T -m 0755 "$dir/git-post-receive" "$path/hooks/post-receive"

set +xe
